export type RouteGroup = {
  label: string;
  routes: { path: string; label: string }[];
};

export const routeGroups: RouteGroup[] = [
  {
    label: 'Editors',
    routes: [
      { path: '/editora-editor', label: 'Editora Editor' },
      { path: '/editora-editor-controlled', label: 'Controlled Editor' },
      { path: '/editora-editor-readonly', label: 'Read-only Editor' },
      { path: '/editora-editor-plugins', label: 'Plugin Toolbar' },
      { path: '/editora-editor-all-toolbars', label: 'All Toolbars' },
      { path: '/editora-editor-enterprise', label: 'Enterprise Editor' },
      { path: '/editora-editor-api', label: 'Editor API' },
      { path: '/light-code-editor', label: 'Light Code Editor' },
      { path: '/light-code-editor-languages', label: 'Languages & Themes' },
      { path: '/light-code-editor-search', label: 'Search & Replace' },
      { path: '/light-code-editor-diagnostics', label: 'Diagnostics' },
      { path: '/light-code-editor-completion', label: 'Completion' },
      { path: '/light-code-editor-formatting', label: 'Formatting' },
      { path: '/light-code-editor-readonly', label: 'Read-only Code' },
      { path: '/light-code-editor-full', label: 'Full Code Editor' },
    ],
  },
  {
    label: 'Motion',
    routes: [
      { path: '/animated-beam', label: 'AnimatedBeam' },
      { path: '/animated-list', label: 'AnimatedList' },
      { path: '/animated-number', label: 'AnimatedNumber' },
      { path: '/animated-text', label: 'AnimatedText' },
      { path: '/marquee', label: 'Marquee' },
      { path: '/number-ticker', label: 'NumberTicker' },
      { path: '/orbiter', label: 'Orbiter' },
      { path: '/spinning-text', label: 'SpinningText' },
    ],
  },
  {
    label: 'Layout',
    routes: [
      { path: '/app-header', label: 'AppHeader' },
      { path: '/aspect-ratio', label: 'AspectRatio' },
      { path: '/box', label: 'Box' },
      { path: '/container', label: 'Container' },
      { path: '/dock', label: 'Dock' },
      { path: '/flex', label: 'Flex' },
      { path: '/grid', label: 'Grid' },
      { path: '/layout', label: 'Layout' },
      { path: '/masonry-grid', label: 'MasonryGrid' },
      { path: '/panel-group', label: 'PanelGroup' },
      { path: '/section', label: 'Section' },
      { path: '/sidebar', label: 'Sidebar' },
    ],
  },
  {
    label: 'Typography & Display',
    routes: [
      { path: '/avatar', label: 'Avatar' },
      { path: '/badge', label: 'Badge' },
      { path: '/breadcrumb', label: 'Breadcrumb' },
      { path: '/icon', label: 'Icon' },
      { path: '/icon-cloud', label: 'IconCloud' },
      { path: '/icons-catalog', label: 'Icons Catalog' },
      { path: '/kbd', label: 'Kbd' },
      { path: '/separator', label: 'Separator' },
      { path: '/shortcut', label: 'Shortcut' },
      { path: '/skeleton', label: 'Skeleton' },
      { path: '/visually-hidden', label: 'VisuallyHidden' },
    ],
  },
  {
    label: 'Buttons & Actions',
    routes: [
      { path: '/button', label: 'Button' },
      { path: '/button-matrices', label: 'Button Matrices' },
      { path: '/copy-button', label: 'CopyButton' },
      { path: '/quick-actions', label: 'QuickActions' },
      { path: '/split-button', label: 'SplitButton' },
      { path: '/toggle', label: 'Toggle' },
      { path: '/toggle-group', label: 'ToggleGroup' },
      { path: '/toolbar', label: 'Toolbar' },
    ],
  },
  {
    label: 'Form Inputs',
    routes: [
      { path: '/checkbox', label: 'Checkbox' },
      { path: '/color-picker', label: 'ColorPicker' },
      { path: '/combobox', label: 'Combobox' },
      { path: '/date-time-field', label: 'DateTimeField' },
      { path: '/date-time-pickers', label: 'Date Time Pickers' },
      { path: '/field', label: 'Field' },
      { path: '/field-semantics', label: 'FieldSemantics' },
      { path: '/file-upload', label: 'FileUpload' },
      { path: '/inline-edit', label: 'InlineEdit' },
      { path: '/input', label: 'Input' },
      { path: '/label', label: 'Label' },
      { path: '/multi-select', label: 'MultiSelect' },
      { path: '/number-field', label: 'NumberField' },
      { path: '/password-field', label: 'PasswordField' },
      { path: '/pin-input', label: 'PinInput' },
      { path: '/radio', label: 'Radio' },
      { path: '/radio-group', label: 'RadioGroup' },
      { path: '/rating', label: 'Rating' },
      { path: '/select', label: 'Select' },
      { path: '/slider', label: 'Slider' },
      { path: '/switch', label: 'Switch' },
      { path: '/tags-input', label: 'TagsInput' },
      { path: '/textarea', label: 'Textarea' },
      { path: '/transfer-list', label: 'TransferList' },
    ],
  },
  {
    label: 'Overlays & Popups',
    routes: [
      { path: '/alert-dialog', label: 'AlertDialog' },
      { path: '/alert-dialog-promise', label: 'AlertDialogPromise' },
      { path: '/context-menu', label: 'ContextMenu' },
      { path: '/dialog', label: 'Dialog' },
      { path: '/dialog-promise', label: 'DialogPromise' },
      { path: '/drawer', label: 'Drawer' },
      { path: '/dropdown', label: 'Dropdown' },
      { path: '/floating-toolbar', label: 'FloatingToolbar' },
      { path: '/hover-card', label: 'HoverCard' },
      { path: '/menu', label: 'Menu' },
      { path: '/menubar', label: 'Menubar' },
      { path: '/popover', label: 'Popover' },
      { path: '/portal', label: 'Portal' },
      { path: '/selection-popup', label: 'SelectionPopup' },
      { path: '/tooltip', label: 'Tooltip' },
    ],
  },
  {
    label: 'Feedback',
    routes: [
      { path: '/accordion', label: 'Accordion' },
      { path: '/alert', label: 'Alert' },
      { path: '/collapsible', label: 'Collapsible' },
      { path: '/empty-state', label: 'EmptyState' },
      { path: '/meter', label: 'Meter' },
      { path: '/presence', label: 'Presence' },
      { path: '/progress', label: 'Progress' },
      { path: '/toast', label: 'Toast' },
      { path: '/toast-api', label: 'ToastAPI' },
    ],
  },
  {
    label: 'Navigation',
    routes: [
      { path: '/breadcrumb', label: 'Breadcrumb' },
      { path: '/command', label: 'Command' },
      { path: '/command-palette', label: 'CommandPalette' },
      { path: '/navigation-menu', label: 'NavigationMenu' },
      { path: '/pagination', label: 'Pagination' },
      { path: '/stepper', label: 'Stepper' },
      { path: '/tabs', label: 'Tabs' },
      { path: '/tree', label: 'Tree' },
      { path: '/wizard', label: 'Wizard' },
    ],
  },
  {
    label: 'Data Display',
    routes: [
      { path: '/calendar', label: 'Calendar' },
      { path: '/card', label: 'Card' },
      { path: '/carousel', label: 'Carousel' },
      { path: '/chart', label: 'Chart' },
      { path: '/code-block', label: 'CodeBlock' },
      { path: '/code-snippet', label: 'CodeSnippet' },
      { path: '/data-table', label: 'DataTable' },
      { path: '/data-view-toolbar', label: 'DataViewToolbar' },
      { path: '/filters-bar', label: 'FiltersBar' },
      { path: '/gantt', label: 'Gantt' },
      { path: '/metric-card', label: 'MetricCard' },
      { path: '/page-header', label: 'PageHeader' },
      { path: '/page-toolbar', label: 'PageToolbar' },
      { path: '/placement-grid', label: 'PlacementGrid' },
      { path: '/record-header', label: 'RecordHeader' },
      { path: '/reporting', label: 'Reporting Dashboard' },
      { path: '/scroll-area', label: 'ScrollArea' },
      { path: '/sortable', label: 'Sortable' },
      { path: '/stat', label: 'Stat' },
      { path: '/table', label: 'Table' },
      { path: '/timeline', label: 'Timeline' },
    ],
  },
  {
    label: 'Primitives',
    routes: [
      { path: '/block-controls', label: 'BlockControls' },
      { path: '/direction-provider', label: 'DirectionProvider' },
      { path: '/form', label: 'Form' },
      { path: '/plugin-panel', label: 'PluginPanel' },
      { path: '/primitive-wrappers', label: 'Primitive Wrappers' },
      { path: '/scroll-area', label: 'ScrollArea' },
      { path: '/slot', label: 'Slot' },
      { path: '/theming', label: 'Theming' },
    ],
  },
];
